### ISSUE TITLE
Hourly Predictions

### ISSUE THREAD

**Issue by darksidelemm** [projecthorus/leaflet_predictor#3]
To provide a replacement for the hourly predictor functionality of the current Habhub ecosystem, I suggest adding an hourly prediction function to this predictor. 

This would consist of:
* Extra UI elements to allow selection of a time step (e.g. 1 hour by default), and then running of multiple predictions starting from the user-specified time, and stepping forward in launch time by the time step.

**Comment by vadhopper** [comment]
I would love to have this hourly predictor functionality as well.   I have been using for 7 years now with my balloon launches in my science classroom.

**Comment by darksidelemm** [comment]
This is currently under test at https://predict-testing.sondehub.org/ !
There's now a dropdown box above the run prediction button to select how the prediction should be run. Give it a go and see what you think!

**Comment by vadhopper** [comment]
Hi Mark,  Thanks for setting this up.  That works great!

**Comment by darksidelemm** [comment]
Now available on the main predictor site!
